
import NavBar from "../components/NavBar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Provider as AuthProvider } from '../context/AuthContext';
import { Provider as TrackProvider } from '../context/TrackContext';
import { dbConnect } from "../lib/db";

import "./globals.css";

export const metadata = {
  title: "TrackMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  dbConnect();
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <TrackProvider>
            <AppRouterCacheProvider>
              <div className="text-white items-center justify-items-center min-h-screen">
                <NavBar />
                {children}
              </div>
            </AppRouterCacheProvider>
          </TrackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
