import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"

import NavBar from "../components/NavBar";
import Footer from "@/components/Footer";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

import { Provider as AuthProvider } from '@/context/AuthContext';
import { Provider as TrackProvider } from '@/context/TrackContext';
import { Provider as CommentProvider } from '@/context/CommentContext'; // Ensure you're using the correct path
import { Provider as InboxProvider } from '@/context/InboxContext';

import "./globals.css";

export const metadata = {
  title: "TrackMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-black/[.7] via-blue-500 to-black">
        <AuthProvider>
          <TrackProvider>
            <CommentProvider>
              <InboxProvider>
                <AppRouterCacheProvider>
                  <div className="text-white flex flex-col min-h-screen">
                    <NavBar />
                    <main className="flex-grow">{children}</main>
                    <Analytics />
                    <SpeedInsights />
                    <Footer />
                  </div>
                </AppRouterCacheProvider>
              </InboxProvider>
            </CommentProvider>
          </TrackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
